-- What each table and the less obvious columns are for. Metadata only.
-- review_events and review_state, and the columns that already have a comment,
-- are left as they were.

comment on table public.admin_audit_log is 'What admins changed, and when. Written after the change, best effort, by writeAudit; actor_email is a snapshot that outlives the account.';
comment on table public.ai_credit_allocations is 'Which credit lots a spend was taken from, and how much from each. Insert-only; a lot''s remaining credits are its amount minus its allocations minus its expire row.';
comment on table public.ai_credit_costs is 'What a credit spend cost us at the provider, in millionths of a dollar. One row per spend.';
comment on table public.ai_credit_ledger is 'Every credit event, insert-only: spend, refund, grant, expire and reset. Grants and refunds are the lots credits are spent from.';
comment on table public.ai_credit_settings is 'Single row (id is always true): the credits switch, the dollar value of a credit and the default margin.';
comment on table public.ai_feature_allowlist is 'People who may use a feature whose access mode is allowlist.';
comment on table public.ai_feature_runs is 'Run guard: at most one AI run per person and feature at a time. The row is the lock; a stale one is taken over after its time limit.';
comment on table public.ai_feature_settings is 'One row per AI feature: switch, who may use it, daily cap, unit and which narration providers are on. billable is fixed; prices live in credit_prices.';
comment on table public.ai_usage_events is 'One row per provider call made for a person, for daily caps and reporting. Never costs credits. Rows older than 90 days are deleted daily by prune_operational_rows().';
comment on table public.ai_worker_status is 'Heartbeat of the narration sync worker, one row per worker and tick source (cron or app), so the admin page can tell when cron stopped.';
comment on table public.audio_jobs is 'One narration clip per term or story and content version. A new version supersedes the old job; the sweeper deletes the file and then the job.';
comment on table public.collection_loves is 'A person''s love for a shared collection. collections.love_count is kept in step by a trigger.';
comment on table public.collection_narration_settings is 'Per collection narration mode, admin only: term speaks the term name, full speaks the term, definition and optional fields. No row means term.';
comment on table public.collection_reports is 'Reports of a shared collection by members; at most one open report per person and collection.';
comment on table public.collection_request_settings is 'Single row (id is always true): whether collection requests are open or paused, and the delivery estimates shown to people.';
comment on table public.collection_requests is 'A person''s request for a collection, built by hand and delivered as a private copy. At most one open request per person.';
comment on table public.collections is 'A set of terms. Owned by one person; visibility says whether others may add it, status flags (is_builtin, is_public) are set by admins.';
comment on table public.credit_grant_policies is 'Rules for automatic credit grants (starter, monthly, self top-up): amount, cadence, expiry and which accounts they apply to. Closed by effective_to, never edited.';
comment on table public.credit_prices is 'What a feature costs in credits, effective-dated per feature. A spend points at the row that priced it.';
comment on table public.import_batches is 'One row per import a person ran, with its result summary.';
comment on table public.issue_reports is 'Problems and ideas people sent from Report an issue, with an optional screenshot in the issue-screenshots bucket. Triaged by admins.';
comment on table public.narration_sync_jobs is 'An admin''s run that generates missing narration for one collection, a few terms per tick. Only one job may be queued or running at a time.';
comment on table public.referral_codes is 'Sign-up codes. A code can be used up to max_uses times; each use is a referral_redemptions row.';
comment on table public.referral_redemptions is 'Which person signed up with which referral code.';
comment on table public.stories is 'AI stories written around a person''s Read queue. segments holds the text; term_ids are the terms it uses.';
comment on table public.story_collection_prefs is 'A person''s story reading level, CEFR level and piece length for one collection.';
comment on table public.telegram_links is 'A person''s Telegram chat link, delivery cadence and the state of an in-progress /quiz or /review in that chat.';
comment on table public.term_relationships is 'A typed link from one term to another, shown on the term card.';
comment on table public.terms is 'A term and its definition, example and notes, in one collection. A term with no definition is unfinished and is left out of study and delivery.';
comment on table public.triage_deferrals is 'Terms a person set aside in Triage with Not yet, to look at again later.';
comment on table public.user_active_collections is 'Which collections a person has switched on for study. Collections they own or added but switched off are not in here.';
comment on table public.user_collections is 'Collections a person has added from others. Collections they own are theirs without a row here.';
comment on table public.user_settings is 'One row per person: preferences, streak, tour progress, analytics consent and term layout.';
comment on table public.users is 'One row per account, same id as auth.users: email, role, suspension and referral state.';
comment on table public.waitlist_requests is 'People who asked for access. normalized_email is the lowercased email used to reject duplicates.';
comment on table public.widget_tokens is 'Tokens for the macOS widget. Only the hash is stored; last_used_at is refreshed at most once an hour.';

comment on column public.audio_jobs.subject_type is 'term or story. With subject_id this names the thing narrated; subject_id has no foreign key because it points at either table.';
comment on column public.audio_jobs.content_hash is 'Hash of what is spoken. A clip is current while its hash matches the content; hash_version says how the hash was computed.';
comment on column public.audio_jobs.status is 'pending, ready, failed or superseded. Only one job per subject is not superseded.';
comment on column public.audio_jobs.user_id is 'The story''s owner; empty for terms. Cleared when the person is deleted, which only happens to superseded jobs.';
comment on column public.ai_credit_ledger.kind is 'spend, refund, grant, expire or reset. Only grant and refund rows are lots.';
comment on column public.ai_credit_ledger.source is 'Where a lot came from: starter, monthly, self_topup, admin, opening, reset or refund. Required for every grant and refund.';
comment on column public.ai_credit_ledger.lot_id is 'On an expire row, the lot it writes off. On a refund row, the lot the credits go back to; null for the refund of a spend from before lots.';
comment on column public.ai_credit_ledger.refund_of is 'On a refund row, the spend it gives back.';
comment on column public.ai_credit_ledger.period_key is 'Which period an automatic grant covers (for example 2026-10), so a policy grants once per period.';
comment on column public.ai_credit_ledger.price_id is 'On a spend row, the credit_prices row that priced it.';
comment on column public.ai_credit_ledger.units is 'On a spend row, how many units of the feature were bought (terms, questions, 1,000 characters).';
comment on column public.collections.visibility is 'private or shared. Set by the owner; a shared collection can be added by others.';
comment on column public.collections.is_builtin is 'Set by admins: part of the built-in library. Owners cannot delete it.';
comment on column public.collections.is_public is 'Set by admins: has a public page. Only a built-in collection can be public.';
comment on column public.collections.slug is 'Address of the public page. Only set on public collections.';
comment on column public.collections.kind is 'terms (jargon) or vocabulary (words and phrases of a language). Changes wording and the quiz questions.';
comment on column public.collections.share_blocked_at is 'When an admin took the collection down from sharing. Set together with share_block_reason.';
comment on column public.terms.slug is 'Address within a public collection. Unique per collection.';
comment on column public.terms.definition is 'Null while the term is unfinished (only a name). Unfinished terms are left out of study, delivery and public pages.';
comment on column public.terms.note is 'The owner''s own note on the term.';
comment on column public.narration_sync_jobs.term_ids is 'The terms still to do, snapshotted when the job starts. Emptied when the job finishes; term_count keeps the size.';
comment on column public.narration_sync_jobs.cursor is 'How many of term_ids have been handled.';
comment on column public.narration_sync_jobs.term_count is 'How many terms the job covered. 0 on jobs made before this column existed; the app then counts term_ids.';
comment on column public.stories.new_term_ids is 'Terms in the story the person had not met yet when it was written; the reader offers to mark them known.';
comment on column public.stories.vote is '-1 or 1 for a thumbs down or up; null if the person did not vote.';
comment on column public.referral_codes.used_by is 'First person to use the code. Kept for the admin people views; every use is also in referral_redemptions.';
comment on column public.users.pending_referral_code is 'A shared code a person typed before their account was verified; used by sign-up, then cleared.';
comment on column public.users.referral_code_ran_out is 'The shared code filled up or expired between sign-up and email confirmation, so the person is asked for a code. Cleared when they redeem one.';
comment on column public.users.suspended_at is 'When an admin suspended the account; null if not suspended.';
comment on column public.collection_requests.kind is 'jargon, vocabulary or definitions. A definitions request fills in the unfinished terms of one of the person''s own collections.';
comment on column public.telegram_links.cadence is 'How often reminders are sent: off, 6h, 12h or 24h.';
comment on column public.widget_tokens.token_hash is 'Hash of the bearer token; the token itself is shown once and never stored.';
