import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { QuizQuestionStyle } from "@/lib/quiz/types";

type QuizQuestionStyleFieldProps = {
  value: QuizQuestionStyle;
  onChange: (style: QuizQuestionStyle) => void;
};

export function QuizQuestionStyleField({ value, onChange }: QuizQuestionStyleFieldProps) {
  return (
    <fieldset className="flex flex-col gap-2 border-0 p-0">
      <legend className="mb-2 text-sm font-medium leading-none">Question style</legend>
      <div className="flex gap-2">
        <Button
          type="button"
          variant="outline"
          onPress={() => onChange("simple")}
          aria-pressed={value === "simple"}
          className={cn(
            "min-h-11 flex-1",
            value === "simple" && "border-primary bg-primary/10 text-primary hover:bg-primary/15",
          )}
        >
          Simple
        </Button>
        <Button
          type="button"
          variant="outline"
          onPress={() => onChange("ai")}
          aria-pressed={value === "ai"}
          className={cn(
            "min-h-11 flex-1",
            value === "ai" && "border-primary bg-primary/10 text-primary hover:bg-primary/15",
          )}
        >
          AI
        </Button>
      </div>
      <p className="m-0 text-xs leading-relaxed text-base-content/60">
        {value === "simple"
          ? "See the definition and pick the correct term."
          : "Comprehension-based questions generated by AI."}
      </p>
    </fieldset>
  );
}
