import { cn } from "@/lib/utils";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import type { QuizQuestionStyle } from "@/lib/quiz/types";

type QuizQuestionStyleFieldProps = {
  value: QuizQuestionStyle;
  onChange: (style: QuizQuestionStyle) => void;
};

/** Both stacked in one cell, so the field keeps the height of the longer one. */
const STYLE_HINTS: { style: QuizQuestionStyle; text: string }[] = [
  { style: "simple", text: "See a definition or example, and pick the correct term." },
  { style: "ai", text: "Comprehension-based questions generated by AI." },
];

export function QuizQuestionStyleField({ value, onChange }: QuizQuestionStyleFieldProps) {
  return (
    <fieldset data-tour="quiz-style" className="flex flex-col gap-2 border-0 p-0">
      <legend className="mb-2 text-sm font-medium leading-none">Question style</legend>
      <ToggleGroup
        aria-label="Question style"
        selectionMode="single"
        disallowEmptySelection
        selectedKeys={[value]}
        onSelectionChange={(keys) => {
          const [key] = [...keys];
          if (key) onChange(key as QuizQuestionStyle);
        }}
        className="flex-nowrap"
      >
        <ToggleGroupItem id="simple" className="flex-1 px-2">
          Simple
        </ToggleGroupItem>
        <ToggleGroupItem id="ai" className="flex-1 px-2">
          AI
        </ToggleGroupItem>
      </ToggleGroup>
      <div className="grid text-xs text-base-content/70">
        {STYLE_HINTS.map((hint) => (
          <p
            key={hint.style}
            className={cn("col-start-1 row-start-1 m-0", hint.style !== value && "invisible")}
          >
            {hint.text}
          </p>
        ))}
      </div>
    </fieldset>
  );
}
